baseURL = 'https://kei-ta.github.io/kei-ta-blog-go/'
languageCode = 'ja'
title = 'Kei-Ta Blog'
theme = "PaperMod"

[params]
  useFontAwesome = true
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Engineer"
    url = "/engineer/"
    weight = 2

  [[menu.main]]
    name = "DIY"
    url = "/diy/"
    weight = 3